import {
  Tags,
  Users,
  Link,
  LayoutGrid,
  Package,
  UserCircle,
  UserCog,
  Receipt,
  Bell,
  BellRing,
  Bookmark,
  CalendarClock,
  Usb,
  CalendarDays,
  FileText,
  Wallet,
  Globe,
} from "lucide-react";

export const settingsOptions = [
  {
    title: "Tags",
    description:
      "Use tags to manage your client and tasks e.g. Urgent, Important.",
    icon: Tags,
    iconBgColor: "bg-red-50",
    iconColor: "text-red-500",
    route: "/settings/tags",
  },
  {
    title: "Client Settings",
    description:
      "Manage client settings and manage custom fields to add more details about clients.",
    icon: Users,
    iconBgColor: "bg-blue-50",
    iconColor: "text-blue-500",
    route: "/settings/client-settings",
  },
  {
    title: "Portals List",
    description: "Manage portals or websites e.g. GST, Income Tax.",
    icon: Link,
    iconBgColor: "bg-orange-50",
    iconColor: "text-orange-500",
    route: "/settings/portals",
  },
  {
    title: "Services",
    description: "Add or edit the services e.g. GST-3B, Audit.",
    icon: LayoutGrid,
    iconBgColor: "bg-purple-50",
    iconColor: "text-purple-500",
    route: "/services",
  },
  {
    title: "Packages",
    description:
      "Add or edit the packages e.g. GST Yearly Package, Complete Accountancy Package.",
    icon: Package,
    iconBgColor: "bg-amber-50",
    iconColor: "text-amber-600",
    route: "/packages",
  },
  {
    title: "Users",
    description: "Add or edit the users, user roles, password and more.",
    icon: UserCircle,
    iconBgColor: "bg-emerald-50",
    iconColor: "text-emerald-500",
    route: "/users",
  },
  {
    title: "User Roles",
    description:
      "Create or edit the user roles and allow or restrict control of the dashboard to users.",
    icon: UserCog,
    iconBgColor: "bg-yellow-50",
    iconColor: "text-yellow-500",
    route: "/settings/roles",
  },
  {
    title: "Billing Settings",
    description: "Customize or create your invoice and receipt formatting.",
    icon: Receipt,
    iconBgColor: "bg-pink-50",
    iconColor: "text-pink-500",
    route: "/settings/billing",
  },
  {
    title: "General Notifications",
    description:
      "Schedule general messages, WhatsApp and email timing and more.",
    icon: Bell,
    iconBgColor: "bg-cyan-50",
    iconColor: "text-cyan-500",
    route: "/settings/notifications",
  },
  {
    title: "Task Notifications",
    description: "Schedule and apply conditions for task reminders.",
    icon: BellRing,
    iconBgColor: "bg-green-50",
    iconColor: "text-green-500",
    route: "/settings/task-notifications",
  },
  {
    title: "Client Groups",
    description: "Add, edit or delete the client's group.",
    icon: Users,
    iconBgColor: "bg-indigo-50",
    iconColor: "text-indigo-500",
    route: "/settings/client-groups",
  },
  {
    title: "Expense Categories",
    description:
      "Manage your expenses using categories e.g. Stationery, Legal expenses.",
    icon: Bookmark,
    iconBgColor: "bg-lime-50",
    iconColor: "text-lime-600",
    route: "/settings/expense-categories",
  },
  {
    title: "Attendance Settings",
    description: "You can set weekend days for attendance.",
    icon: CalendarClock,
    iconBgColor: "bg-red-50",
    iconColor: "text-red-400",
    route: "/settings/attendance",
  },
  {
    title: "DSC Settings",
    description:
      "Change automatic task creation settings for DSC (Digital Signature Certificate)",
    icon: Usb,
    iconBgColor: "bg-cyan-50",
    iconColor: "text-cyan-400",
    route: "/settings/dsc",
  },
  {
    title: "Holidays List",
    description: "Create or change the holidays list for attendance.",
    icon: CalendarDays,
    iconBgColor: "bg-blue-50",
    iconColor: "text-blue-400",
    route: "/settings/holidays",
  },
  {
    title: "Document Types",
    description:
      "Add or delete document type e.g. Income Tax Return, Client's PAN card.",
    icon: FileText,
    iconBgColor: "bg-violet-50",
    iconColor: "text-violet-500",
    route: "/settings/document-types",
  },
  {
    title: "Payment Modes",
    description:
      "Add or delete payment modes for receipt and expense vouchers e.g. Bank, Cheque, Cash.",
    icon: Wallet,
    iconBgColor: "bg-orange-50",
    iconColor: "text-orange-400",
    route: "/settings/payment-modes",
  },
  {
    title: "Website Settings",
    description:
      "Configure your website settings e.g. Logo, Service, Contact details and more.",
    icon: Globe,
    iconBgColor: "bg-sky-50",
    iconColor: "text-sky-500",
    route: "/settings/website",
  },
];
